In [50]:
import pandas as pd
import numpy as np
import re

In [153]:
df_attr = pd.read_csv('London_attraction.csv')
df_hotel_info = pd.read_csv('hotel_info.csv')
df_hotel_url = pd.read_csv('hotel_url_london.csv')
df_hotel = pd.merge(df_hotel_url[['hotel_id', 'hotel_name','Price']], df_hotel_info)

In [154]:
df_attr

name  \
0                        Tower of London   
1                           Tower Bridge   
2                    Churchill War Rooms   
3                       National Gallery   
4                     The British Museum   
5                      Westminster Abbey   
6      V&A  - Victoria and Albert Museum   
7                   St. Paul's Cathedral   
8                 Natural History Museum   
9                         Borough Market   
10                             Hyde Park   
11                          Up at The O2   
12                      St. James's Park   
13                         Covent Garden   
14                  Houses of Parliament   
15                         Camden Market   
16      Chelsea FC Stadium Tour & Museum   
17               The View from The Shard   
18                            Sky Garden   
19                         Regent's Park   
20      Emirates Stadium Tour and Museum   
21                     Buckingham Palace   
22                    Wallace Collection   
23                             Greenwich   
24                  Imperial War Museums   
25                           HMS Belfast   
26                     Highgate Cemetery   
27           Shakespeare's Globe Theatre   
28            School Of Rock The Musical   
29         Royal Air Force Museum London   
..                                   ...   
270                       One New Change   
271          Crossrail Place Roof Garden   
272                      Garrick Theatre   
273                       Russell Square   
274                  Royal Festival Hall   
275  Church of St. Bartholomew the Great   
276   Plaza Premium Lounge T5 Departures   
277                      Duchess Theatre   
278                    Golders Hill Park   
279             All Hallows By The Tower   
280                      Adelphi Theatre   
281                             The Mall   
282                         Baker Street   
283                    Parliament Square   
284              Bomber Command Memorial   
285                     The Arts Theatre   
286                    Hippodrome Casino   
287                    Criterion Theatre   
288                  Billingsgate Market   
289                       London Stadium   
290                      Nelson's Column   
291           Peter Harrison Planetarium   
292                          The Old Vic   
293                      The London Pass   
294                           Old Bailey   
295                 The UK Supreme Court   
296                       Sadler's Wells   
297                         Fenton House   
298                  County Hall, London   
299                         London Buses   

                                               address  rate   price  rank  \
0    St Katharine's & Wapping, London EC3N 4AB England   4.5  £28.90     8   
1            Tower Bridge Road, London SE1 2UP England   4.5   £9.80     6   
2    King Charles Street, Clive Steps Westminster, ...   4.5  £23.00     2   
3            Trafalgar Square, London WC2N 5DN England   4.5       0     1   
4        Great Russell Street, London WC1B 3DG England   4.5       0     4   
5    20 Dean's Yard Broad Sanctuary, London SW1P 3P...   4.5  £22.00    11   
6                Cromwell Road, London SW7 2RL England   4.5       0     5   
7        St Paul's Churchyard, London EC4M 8AD England   4.5  £17.00    13   
8    Cromwell Road South Kensington, London SW7 5BD...   4.5       0    12   
9           8 Southwark Street, London SE1 1TL England   4.5       0    10   
10                               London W2 2UH England   4.5       0     7   
11                     The O2, London SE10 0DX England   4.5       0    25   
12   Horse Guards Road The Storeyard, London SW1A 2...   4.5       0     3   
13              Covent Garden, London WC2E 9DD England   4.5       0    15   
14          Parliament Square, London SW1A 0AA England   4.5       0     9   
15        32 Camden Lock Place, London NW1 8AF England   4.

In [155]:
df_hotel

hotel_id                                         hotel_name Price  \
0           1                        SponsoredLondon House Hotel  £102   
1           2               Park Plaza Westminster Bridge London  £173   
2           3                                    The Tower Hotel  £141   
3           4                                   K+K Hotel George  £186   
4           5                                 London House Hotel  £102   
5           6  Corus Hyde Park Hotel, Sure Hotel Collection b...  £109   
6           7    SponsoredThe Chronicle by Supercity Aparthotels  £163   
7           8                        Novotel London Canary Wharf  £210   
8           9                             Qbic Hotel London City   £61   
9          10             Copthorne Tara Hotel London Kensington   £78   
10         11                          Holiday Inn London - West   £86   
11         12                     citizenM Tower of London Hotel   £99   
12         13                Staybridge Suites London - Vauxhall  £128   
13         14                               Novotel London Excel  £114   
14         15  Studios2Let Serviced Apartments - Cartwright G...   £78   
15         16                             Hard Rock Hotel London  £130   
16         17                                Dorsett City London  £134   
17         18                                 The W14 Kensington   £59   
18         19                                   St. Athans Hotel   £92   
19         20        Holiday Inn London - Kensington High Street  £102   
20         21                       Best Western Victoria Palace  £104   
21         22                               The Westbridge Hotel  £100   
22         23                    Mercure London Paddington Hotel   £89   
23         24                Holiday Inn London Kensington Forum   £90   
24         25      Millennium Gloucester Hotel London Kensington   £97   
25         26                          The Bailey's Hotel London  £125   
26         27                          The Chelsea Harbour Hotel  £184   
27         28                         citizenM London Shoreditch   £99   
28         29              Best Western Chiswick Palace & Suites   £65   
29         30                                        Leman Locke   £99   
..        ...                                                ...   ...   
290       291       Taj 51 Buckingham Gate Suites and Residences  £396   
291       292                                Montagu Place Hotel  £214   
292       293                               The Cavendish London  £255   
293       294                          The Sanctuary House Hotel  £237   
294       295                 SponsoredThe Prince Akatoki London  £383   
295       296                                     The Devonshire  £168   
296       297                                      The Half Moon  £182   
297       298                      Andaz London Liverpool Street  £237   
298       299                              Nobu Hotel Shoreditch  £219   
299       300                                    St Paul's Hotel  £235   
300       301   Lincoln Plaza London, Curio Collection by Hilton  £154   
301       302                      The Grand at Trafalgar Square  £208   
302       303                                 Karma Sanctum Soho  £194   
303       304                    Crowne Plaza London - Battersea  £122   
304       305                              The Fox & Goose Hotel  £170   
305       306                   Mornington Hotel London Victoria  £127   
306       307                Ibis Styles London Kensington Hotel  £133   
307       308                                  Grove Guest House   £80   
308       309                 Ibis London Docklands Canary Wharf  £108   
309       310        Holiday Inn London - Kensington High Street  £117   
310       311                          Citadines Barbican London  £141   
311       312                             Clayton Hotel Chiswick  £111   
312      

### Hotel - Review Score

In [233]:
def review_score_calculating(df):
    df_review = df[['n_Excellent', 'n_VeryGood', 'n_Average', 'n_Poor', 'n_Terrible']]
    total_score = df_review['n_Excellent'] * 5.0 + df_review['n_VeryGood'] * 4.0 \
               + df_review['n_Average'] * 3.0 + df_review['n_Poor'] * 2.0 \
               + df_review['n_Terrible'] * 1.0
    review_count = df_review['n_Excellent'] + df_review['n_VeryGood'] + df_review['n_Average']\
                 + df_review['n_Poor'] + df_review['n_Terrible']
    max_review_count = max(review_count)
    
    return (total_score / (review_count * 5.0) *(review_count / max_review_count)).tolist()

hotel_review_score = review_score_calculating(df_hotel)

In [235]:
hotel_review_score

[0.10737970805550551,
 0.8611191205622635,
 0.3785907370697423,
 0.19537754550369438,
 0.10737970805550551,
 0.16710218057307621,
 0.0025049558479005225,
 0.056433591638133,
 0.19367453595242387,
 0.2646963416831861,
 0.04612542800504595,
 0.15238781762479725,
 0.05182915840692017,
 0.10564065597404938,
 0.10761398450171203,
 0.01941791313750225,
 0.025292845557758153,
 0.0670481167777978,
 0.028825013515948822,
 0.06053342944674716,
 0.06028113173544783,
 0.08350153180753289,
 0.07080555054964857,
 0.16481347990628942,
 0.20109929717066138,
 0.05878536673274464,
 0.09190845197332852,
 0.05896557938367274,
 0.04137682465309065,
 0.031978734907190484,
 0.08770949720670392,
 0.07395026130834385,
 0.06147053523157325,
 0.19132276085781222,
 0.26179491800324384,
 0.14175527122003967,
 0.01973328527662642,
 0.24280050459542257,
 0.0029554874752207604,
 0.01881420075689313,
 0.09379167417552711,
 0.13083438457379706,
 0.19808073526761577,
 0.18402414849522436,
 0.10543341142548208,
 0.189439

### Hotel - Amenity Property 

In [159]:
amenities = df_hotel['Amenities']
all_amenity = {}
for amen in amenities:
    a_split = amen.split(',')
    for idx, a in enumerate(a_split):
        if idx < (len(a_split) - 1):
            term = a[2:-1]
            all_amenity[term] = all_amenity.get(term, 0) + 1
        else:
            term = a[2:-2]
            all_amenity[term] = all_amenity.get(term, 0) + 1


#### Extract high frequency amenities

In [236]:
hf_amenities_tuple = sorted(all_amenity.items(), key = lambda all_amenity:all_amenity[1], reverse = True)[:20]
hf_amenities_tuple

[('Non-smoking rooms', 318),
 ('Wifi', 312),
 ('Flatscreen TV', 309),
 ('Non-smoking hotel', 299),
 ('24-hour front desk', 282),
 ('Free High Speed Internet (WiFi)', 279),
 ('Baggage storage', 270),
 ('Air conditioning', 262),
 ('Breakfast buffet', 260),
 ('Safe', 255),
 ('Laundry service', 251),
 ('Bar / lounge', 249),
 ('Dry cleaning', 233),
 ('Housekeeping', 230),
 ('Restaurant', 229),
 ('Complimentary instant cofffee', 209),
 ('Breakfast available', 207),
 ('Meeting rooms', 202),
 ('Concierge', 190),
 ('Room service', 190)]

In [237]:
hf_amenities = [a[0] for a in hf_amenities_tuple]
hf_amenities

['Non-smoking rooms',
 'Wifi',
 'Flatscreen TV',
 'Non-smoking hotel',
 '24-hour front desk',
 'Free High Speed Internet (WiFi)',
 'Baggage storage',
 'Air conditioning',
 'Breakfast buffet',
 'Safe',
 'Laundry service',
 'Bar / lounge',
 'Dry cleaning',
 'Housekeeping',
 'Restaurant',
 'Complimentary instant cofffee',
 'Breakfast available',
 'Meeting rooms',
 'Concierge',
 'Room service']

In [219]:
# amenity property -> id
amen2id = {}
for idx, amen in enumerate(hf_amenities):
    amen2id[amen] = idx
    
# id -> amenity property 
id2amen = {}
for idx, amen in enumerate(hf_amenities):
    id2amen[idx] = amen
    
def amen2vec(user_amen, method2id):
    ua2vec = np.zeros(20)
    for ua in user_amen:
        idx = method2id[ua]
        ua2vec[idx] = 1
    return ua2vec

def preference_score(user_prefer, items_vec, method):
    # vectorize prefering items user chosen 
    prefer_vec = method(user_prefer)
    
    # get similarity
    similarity = prefer_vec * items_vec   
        
    # num of amenities user wanted
    total_ua = len(user_amen)
    
    return np.sum(similarity) / total_ua 

def preprocessing(am, hf):
    am_new = []
    a_split = am.split(',')
    for idx, a in enumerate(a_split):
        if idx < (len(a_split) - 1):
            term = a[2:-1]
            if term in hf:
                am_new.append(term)
        else:
            term = a[2:-2]
            if term in hf:
                am_new.append(term)
    return am_new


In [217]:
ams = []
for a in amenities:
    a_tmp = preprocessing(a, hf_amenities)
    ams.append(a_tmp)
ams

[['Free High Speed Internet (WiFi)',
  'Wifi',
  'Breakfast available',
  'Baggage storage',
  '24-hour front desk',
  'Breakfast buffet',
  'Complimentary instant cofffee',
  'Non-smoking hotel',
  'Air conditioning',
  'Housekeeping',
  'Safe',
  'Flatscreen TV',
  'Non-smoking rooms'],
 ['Bar / lounge',
  'Wifi',
  'Restaurant',
  'Breakfast available',
  'Breakfast buffet',
  'Complimentary instant cofffee',
  'Meeting rooms',
  'Baggage storage',
  'Concierge',
  'Non-smoking hotel',
  '24-hour front desk',
  'Dry cleaning',
  'Laundry service',
  'Air conditioning',
  'Housekeeping',
  'Room service',
  'Safe',
  'Flatscreen TV',
  'Non-smoking rooms'],
 ['Free High Speed Internet (WiFi)',
  'Bar / lounge',
  'Wifi',
  'Restaurant',
  'Breakfast available',
  'Breakfast buffet',
  'Meeting rooms',
  'Baggage storage',
  'Concierge',
  'Non-smoking hotel',
  '24-hour front desk',
  'Dry cleaning',
  'Laundry service',
  'Air conditioning',
  'Housekeeping',
  'Room service',
  'Sa

In [173]:
ams2vec = [amen2vec(a, amen2id) for a in ams]

### Hotel - Price

In [177]:
def price_preprocessing(price_orig):
    price_processed = re.sub('[^0-9]', '', price_orig)
    return price_processed

In [180]:
hotel_price = df_hotel['Price']
hotel_price_processed = [int(price_preprocessing(p)) for p in hotel_price]

In [181]:
hotel_price_processed

[102,
 173,
 141,
 186,
 102,
 109,
 163,
 210,
 61,
 78,
 86,
 99,
 128,
 114,
 78,
 130,
 134,
 59,
 92,
 102,
 104,
 100,
 89,
 90,
 97,
 125,
 184,
 99,
 65,
 99,
 85,
 192,
 134,
 209,
 567,
 478,
 258,
 298,
 383,
 159,
 244,
 227,
 233,
 118,
 191,
 234,
 133,
 89,
 184,
 133,
 180,
 182,
 61,
 118,
 96,
 100,
 134,
 96,
 90,
 122,
 145,
 105,
 120,
 78,
 383,
 260,
 366,
 359,
 348,
 320,
 134,
 222,
 222,
 221,
 250,
 199,
 242,
 260,
 153,
 280,
 212,
 195,
 210,
 202,
 203,
 74,
 158,
 108,
 99,
 111,
 115,
 56,
 131,
 99,
 155,
 129,
 383,
 579,
 327,
 383,
 156,
 246,
 260,
 257,
 244,
 206,
 180,
 164,
 187,
 193,
 157,
 164,
 108,
 166,
 284,
 127,
 170,
 204,
 98,
 123,
 132,
 165,
 112,
 85,
 130,
 126,
 91,
 84,
 383,
 351,
 314,
 260,
 186,
 210,
 72,
 291,
 114,
 190,
 180,
 142,
 116,
 116,
 206,
 149,
 120,
 109,
 197,
 78,
 160,
 170,
 124,
 107,
 205,
 160,
 130,
 95,
 98,
 142,
 95,
 73,
 383,
 324,
 421,
 198,
 280,
 260,
 134,
 226,
 224,
 218,
 205,
 184,
 2

In [182]:
avg_price = np.sum(hotel_price_processed) / len(hotel_price_processed)

181.425

In [240]:
hotel_price_score = avg_price / (avg_price + hotel_price_processed)
hotel_price_score

array([0.64011643, 0.51188545, 0.562689  , 0.49377424, 0.64011643,
       0.62468796, 0.52674748, 0.46349875, 0.74837579, 0.69933507,
       0.67841451, 0.64696443, 0.58632948, 0.61411526, 0.69933507,
       0.58256402, 0.57517635, 0.75460123, 0.66352748, 0.64011643,
       0.63563108, 0.64466554, 0.67088842, 0.66841669, 0.65161174,
       0.59206984, 0.49647671, 0.64696443, 0.73622806, 0.64696443,
       0.68096087, 0.48584053, 0.57517635, 0.46468592, 0.24240906,
       0.27512606, 0.41286909, 0.37842207, 0.32143332, 0.53293677,
       0.4264559 , 0.4442064 , 0.43777523, 0.60591133, 0.48714506,
       0.43672143, 0.57700565, 0.67088842, 0.49647671, 0.57700565,
       0.50197136, 0.49920892, 0.74837579, 0.60591133, 0.65396053,
       0.64466554, 0.57517635, 0.65396053, 0.66841669, 0.5979237 ,
       0.55579383, 0.63341189, 0.60189102, 0.69933507, 0.32143332,
       0.41099847, 0.33141526, 0.33570801, 0.3426831 , 0.36181882,
       0.57517635, 0.44971184, 0.44971184, 0.45082935, 0.42052

### Hotel - DataFrame

In [248]:
df_hotel_score = pd.DataFrame({'Hotel_Name' : df_hotel['hotel_name'].tolist() , 'Review_score': hotel_review_score, 'Price_score' : hotel_price_score, 'Amenities_vec' : ams2vec})

In [249]:
df_hotel_score

Hotel_Name  Review_score  \
0                          SponsoredLondon House Hotel      0.107380   
1                 Park Plaza Westminster Bridge London      0.861119   
2                                      The Tower Hotel      0.378591   
3                                     K+K Hotel George      0.195378   
4                                   London House Hotel      0.107380   
5    Corus Hyde Park Hotel, Sure Hotel Collection b...      0.167102   
6      SponsoredThe Chronicle by Supercity Aparthotels      0.002505   
7                          Novotel London Canary Wharf      0.056434   
8                               Qbic Hotel London City      0.193675   
9               Copthorne Tara Hotel London Kensington      0.264696   
10                           Holiday Inn London - West      0.046125   
11                      citizenM Tower of London Hotel      0.152388   
12                 Staybridge Suites London - Vauxhall      0.051829   
13                                Novotel London Excel      0.105641   
14   Studios2Let Serviced Apartments - Cartwright G...      0.107614   
15                              Hard Rock Hotel London      0.019418   
16                                 Dorsett City London      0.025293   
17                                  The W14 Kensington      0.067048   
18                                    St. Athans Hotel      0.028825   
19         Holiday Inn London - Kensington High Street      0.060533   
20                        Best Western Victoria Palace      0.060281   
21                                The Westbridge Hotel      0.083502   
22                     Mercure London Paddington Hotel      0.070806   
23                 Holiday Inn London Kensington Forum      0.164813   
24       Millennium Gloucester Hotel London Kensington      0.201099   
25                           The Bailey's Hotel London      0.058785   
26                           The Chelsea Harbour Hotel      0.091908   
27                          citizenM London Shoreditch      0.058966   
28               Best Western Chiswick Palace & Suites      0.041377   
29                                         Leman Locke      0.031979   
..                                                 ...           ...   
290       Taj 51 Buckingham Gate Suites and Residences      0.086466   
291                                Montagu Place Hotel      0.032519   
292                               The Cavendish London      0.191963   
293                          The Sanctuary House Hotel      0.072211   
294                 SponsoredThe Prince Akatoki London      0.002955   
295                                     The Devonshire      0.000811   
296                                      The Half Moon      0.012768   
297                      Andaz London Liverpool Street      0.181051   
298                              Nobu Hotel Shoreditch      0.015841   
299                                    St Paul's Hotel      0.027509   
300   Lincoln Plaza London, Curio Collection by Hilton      0.007317   
301                      The Grand at Trafalgar Square      0.073464   
302                                 Karma Sanctum Soho      0.032204   
303                    Crowne Plaza London - Battersea      0.062471   
304                              The Fox & Goose Hotel      0.053289   
305                   Mornington Hotel London Victoria      0.009659   
306                Ibis Styles London Kensington Hotel      0.052307   
307                                  Grove Guest House      0.008101   
308                 Ibis London Docklands Canary Wharf      0.036457   
309        Holiday Inn London - Kensington High Street      0.060533   
310                          Citadines Barbican London      0.012966   
311                             Clayton Hotel Chiswick      0.042296   
312                         Thistle Kensington Gardens      0.101694   
313                                        Leman Locke      0.031979   
314         

### Attraction - Preference Score

In [187]:
attraction_type = df_attr['attraction type']
all_type = {}
for at in attraction_type:
    at_split = at.split(',')
    for idx, at in enumerate(at_split):
        if idx < (len(at_split) - 1):
            term = at[2:-1]
            all_type[term] = all_type.get(term, 0) + 1
        else:
            term = at[2:-2]
            all_type[term] = all_type.get(term, 0) + 1 

In [238]:
hf_type_tuple = sorted(all_type.items(), key = lambda all_type:all_type[1], reverse = True)[:30]
hf_type_tuple

[('Sights & Landmarks', 141),
 ('Museums', 74),
 ('More', 65),
 ('Points of Interest & Landmarks', 55),
 ('Concerts & Shows', 48),
 ('Theatres', 48),
 ('Speciality Museums', 34),
 ('Historic Sites', 31),
 ('Nature & Parks', 31),
 ('Other', 28),
 ('Shopping', 27),
 ('Neighbourhoods', 27),
 ('Art Museums', 26),
 ('Architectural Buildings', 22),
 ('History Museums', 20),
 ('Flea & Street Markets', 15),
 ('Arenas & Stadiums', 12),
 ('Gardens', 10),
 ('Churches & Cathedrals', 8),
 ('Monuments & Statues', 8),
 ('Food & Drink', 8),
 ('Observation Decks & Towers', 7),
 ('Transportation', 7),
 ('Sacred & Religious Sites', 6),
 ('Mass Transportation Systems', 5),
 ('Fun & Games', 5),
 ('Historic Walking Areas', 5),
 ('Shopping Malls', 5),
 ('Distilleries', 5),
 ('Military Museums', 4)]

In [239]:
hf_type = [t[0] for t in hf_type_tuple]
hf_type

['Sights & Landmarks',
 'Museums',
 'More',
 'Points of Interest & Landmarks',
 'Concerts & Shows',
 'Theatres',
 'Speciality Museums',
 'Historic Sites',
 'Nature & Parks',
 'Other',
 'Shopping',
 'Neighbourhoods',
 'Art Museums',
 'Architectural Buildings',
 'History Museums',
 'Flea & Street Markets',
 'Arenas & Stadiums',
 'Gardens',
 'Churches & Cathedrals',
 'Monuments & Statues',
 'Food & Drink',
 'Observation Decks & Towers',
 'Transportation',
 'Sacred & Religious Sites',
 'Mass Transportation Systems',
 'Fun & Games',
 'Historic Walking Areas',
 'Shopping Malls',
 'Distilleries',
 'Military Museums']

In [206]:
hf_type = ['Sights & Landmarks',
 'Museums',
 'Points of Interest & Landmarks',
 'Concerts & Shows',
 'Theatres',
 'Historic Sites',
 'Nature & Parks',
 'Shopping',
 'Neighbourhoods',
 'Art Museums',
 'Architectural Buildings',
 'Flea & Street Markets',
 'Arenas & Stadiums',
 'Gardens',
 'Churches & Cathedrals',
 'Monuments & Statues',
 'Food & Drink',
 'Transportation',
 'Fun & Games',
 'Shopping Malls']

len(hf_type)

20

In [223]:
# attraction type -> id
attr2id = {}
for idx, typ in enumerate(hf_type):
    attr2id[typ] = idx
    
# id -> attraction type
id2attr = {}
for idx, typ in enumerate(hf_type):
    id2attr[idx] = idx

In [218]:
attr_type = df_attr['attraction type']
types = []
for a in attr_type:
    a_tmp = amenitity_preprocessing(a, hf_type)
    types.append(a_tmp)
types

[['Sights & Landmarks', 'Points of Interest & Landmarks', 'Historic Sites'],
 ['Sights & Landmarks', 'Points of Interest & Landmarks'],
 ['Sights & Landmarks', 'Museums', 'Historic Sites'],
 ['Museums', 'Art Museums'],
 ['Museums', 'Art Museums'],
 ['Sights & Landmarks', 'Historic Sites', 'Architectural Buildings'],
 ['Museums', 'Art Museums'],
 ['Sights & Landmarks', 'Churches & Cathedrals'],
 ['Museums'],
 ['Shopping', 'Flea & Street Markets'],
 ['Nature & Parks'],
 ['Sights & Landmarks'],
 ['Nature & Parks'],
 ['Sights & Landmarks',
  'Shopping',
  'Points of Interest & Landmarks',
  'Flea & Street Markets'],
 ['Sights & Landmarks', 'Historic Sites', 'Architectural Buildings'],
 ['Shopping', 'Flea & Street Markets'],
 ['Sights & Landmarks', 'Arenas & Stadiums'],
 ['Sights & Landmarks',
  'Architectural Buildings',
  'Points of Interest & Landmarks'],
 ['Sights & Landmarks'],
 ['Nature & Parks'],
 ['Museums', 'Sights & Landmarks', 'Arenas & Stadiums'],
 ['Sights & Landmarks', 'Histor

In [228]:
type2vec = [amen2vec(t, attr2id) for t in types]
type2vec

[array([1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([0., 0., 0., 

### Attraction - Review Score

In [242]:
attr_review_score = review_score_calculating(df_attr)

In [243]:
attr_review_score

[0.6914661693328854,
 0.41321486904444726,
 0.2469239056146976,
 0.4298191759241025,
 0.7803885227101601,
 0.25488201837200414,
 0.34130457446685275,
 0.17752962572543932,
 0.38606693155096317,
 0.1406512446859036,
 0.2345986771230322,
 0.06869693143512458,
 0.2016981940760133,
 0.2544117136006116,
 0.17756206053725948,
 0.29648893162046636,
 0.027564956502600577,
 0.1869310876087435,
 0.16042952957939,
 0.06881045327649518,
 0.02767847834397118,
 0.29200134372791825,
 0.07075190844115978,
 0.06212193172472112,
 0.10677308373973379,
 0.039556569786972785,
 0.01905313517207826,
 0.08918414864410903,
 0.010504245485190033,
 0.03871789822419405,
 0.020308825743973496,
 0.046974874604700734,
 0.04130109930844347,
 0.05914487935408389,
 0.06026388036187984,
 0.04137291924890243,
 0.01848784273749812,
 0.028341075214011836,
 0.005986539553094628,
 0.08100362574860703,
 0.006570366165857727,
 0.4515713507940737,
 0.028901734104046246,
 0.8593232708190949,
 0.016838300879215076,
 0.01386819882

### Attraction - DataFrame

In [247]:
df_attr_score = pd.DataFrame({'Attraction Name': df_attr['name'].tolist() ,'Review_score': attr_review_score, 'Preference Score' : type2vec})
df_attr_score

Attraction Name  Review_score  \
0                        Tower of London      0.691466   
1                           Tower Bridge      0.413215   
2                    Churchill War Rooms      0.246924   
3                       National Gallery      0.429819   
4                     The British Museum      0.780389   
5                      Westminster Abbey      0.254882   
6      V&A  - Victoria and Albert Museum      0.341305   
7                   St. Paul's Cathedral      0.177530   
8                 Natural History Museum      0.386067   
9                         Borough Market      0.140651   
10                             Hyde Park      0.234599   
11                          Up at The O2      0.068697   
12                      St. James's Park      0.201698   
13                         Covent Garden      0.254412   
14                  Houses of Parliament      0.177562   
15                         Camden Market      0.296489   
16      Chelsea FC Stadium Tour & Museum      0.027565   
17               The View from The Shard      0.186931   
18                            Sky Garden      0.160430   
19                         Regent's Park      0.068810   
20      Emirates Stadium Tour and Museum      0.027678   
21                     Buckingham Palace      0.292001   
22                    Wallace Collection      0.070752   
23                             Greenwich      0.062122   
24                  Imperial War Museums      0.106773   
25                           HMS Belfast      0.039557   
26                     Highgate Cemetery      0.019053   
27           Shakespeare's Globe Theatre      0.089184   
28            School Of Rock The Musical      0.010504   
29         Royal Air Force Museum London      0.038718   
..                                   ...           ...   
270                       One New Change      0.003371   
271          Crossrail Place Roof Garden      0.006663   
272                      Garrick Theatre      0.017024   
273                       Russell Square      0.007567   
274                  Royal Festival Hall      0.002377   
275  Church of St. Bartholomew the Great      0.002699   
276   Plaza Premium Lounge T5 Departures      0.001154   
277                      Duchess Theatre      0.000526   
278                    Golders Hill Park      0.003028   
279             All Hallows By The Tower      0.002947   
280                      Adelphi Theatre      0.002261   
281                             The Mall      0.007291   
282                         Baker Street      0.001677   
283                    Parliament Square      0.002917   
284              Bomber Command Memorial      0.002766   
285                     The Arts Theatre      0.001052   
286                    Hippodrome Casino      0.000878   
287                    Criterion Theatre      0.001765   
288                  Billingsgate Market      0.002194   
289                       London Stadium      0.001406   
290                      Nelson's Column      0.001853   
291           Peter Harrison Planetarium      0.001070   
292                          The Old Vic      0.002338   
293                      The London Pass      0.001733   
294                           Old Bailey      0.001411   
295                 The UK Supreme Court      0.000616   
296                       Sadler's Wells      0.008234   
297                         Fenton House      0.008004   
298                  County Hall, London      0.002004   
299                         London Buses      0.011714   

                                      Preference Score  
0    [1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...  
1    [1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
5    [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...  
6    [0.0, 1.0, 0.0, 0.0, 0.0

###  EXT Attraction - Weather

### EXT Hotel - Distance